port: 8000
logLevel: 'debug'
enableSwagger: true
auth:
  secret: 'local_secret_key'
db:
  postgres:
    host: 127.0.0.1
    port: 5432
    username: 'postgres'
    password: 'example'
    database: 'postgres'
